version: '3'

networks:
  host:

services:
  practica-jms-main:
    image: ejnunez1311/practica-jms-main

    container_name:  practica-jms-main
    
    ports:
      - 8080:4567

    networks:
      - host

  practica-jms-msj:
    image: ejnunez1311/practica-jms-msj

    container_name:  practica-jms-msj

    ports:
      - 61616:61616

    networks:
      - host
